### ISSUE TITLE
Fatal error: 'try!' expression unexpectedly raised an error

### ISSUE THREAD

**Issue by OldhamMade** [uptech/git-cl#44]
Hey, I've installed `git-cl` via `brew`, tried to run `git cl unreleased`, and I'm getting the following. I've included software versions of everything that might be relevant. Would be great to get this resolved!

```shell
# git cl unreleased
Fatal error: 'try!' expression unexpectedly raised an error: GitChangelog.GitShell.Error.gitLogFailure: file GitChangelog/ReleaseDetails.swift, line 19
error: git-cl died of signal 4

# swift --version
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.6.0

# pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 12.1.0.0.1.1602137645
volume: /
location: /
install-time: 1605182231
groups: com.apple.FindSystemFiles.pkg-group

# brew --version
Homebrew 2.5.9-52-g8cffae8
Homebrew/homebrew-core (git revision cb774; last commit 2020-11-12)
Homebrew/homebrew-cask (git revision 40e5d; last commit 2020-11-12)

# make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

# sw_vers -productVersion
10.15.7
```

**Comment by OldhamMade** [comment]
Confirmed this also fails running on Ubuntu via GitHub Actions:

```shell
Fatal error: 'try!' expression unexpectedly raised an error: GitChangelog.GitShell.Error.gitLogFailure: file GitChangelog/ReleaseDetails.swift, line 19

Current stack trace:
0    libswiftCore.so                    0x00007f50207ca610 swift_reportError + 50
1    libswiftCore.so                    0x00007f502083dea0 _swift_stdlib_reportFatalErrorInFile + 115
2    libswiftCore.so                    0x00007f50205239f5 <unavailable> + 1399285
3    libswiftCore.so                    0x00007f5020523637 <unavailable> + 1398327
4    libswiftCore.so                    0x00007f5020523bd2 <unavailable> + 1399762
5    libswiftCore.so                    0x00007f5020522070 _assertionFailure(_:_:file:line:flags:) + 517
6    libswiftCore.so                    0x00007f502056f919 <unavailable> + 1710361
7    git-cl                             0x0000556b67daaa63 <unavailable> + 539235
8    git-cl                             0x0000556b67d947a1 <unavailable> + 448417
9    git-cl                             0x0000556b67d92a7a <unavailable> + 440954
10   git-cl                             0x0000556b67d546fe <unavailable> + 186110
11   git-cl                             0x0000556b67dac053 <unavailable> + 544851
12   libc.so.6                          0x00007f501ea03b10 __libc_start_main + 231
13   git-cl                             0x0000556b67d404ea <unavailable> + 103658
error: git-cl died of signal 4
```

Here's the detail of the job I'm running:
```yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
      - name: Install git-ci
        run: |
          cd /tmp/
          git clone https://github.com/uptech/git-cl.git git-cl
          cd ./git-cl
          make -j$(nproc)
          sudo make install
          cd -
      - name: Generate Changelog
        run: |
          git cl full
```

I'm keen to get this tool integrated into my workflow, so any suggestions on workaround or an idea on when we can expect a fix release would be great!

**Comment by OldhamMade** [comment]
FYI, I've also confirmed this error with Swift 5.2 using:
```yml
  - uses: fwal/setup-swift@v1
    with:
      swift-version: "5.2"
```
